function initializeTracks
% create an empty array of tracks

global tracks 
tracks = struct(...
    'id', {}, ...
    'object', {}, ...
    'location', {},...
    'frame', {}, ...
    'age', {}, ...
    'totalVisibleCount', {}, ...
    'consecutiveInvisibleCount', {});
end